config/routes.rb
Mersea::Application.routes.draw do
  devise_for :users

  root :to => 'guests#index'
  
  resources :events

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match 'events' => 'events#create', :as => 'events', :via => :post

  match ':controller(/:action(/:id))(.:format)'

  scope "(:locale)", :locale => /en|fr/ do
    match 'multimedia' => 'guests#multimedia', :as => :multimedia
    match 'included' => 'guests#included', :as => :included
    match 'pricing' => 'guests#pricing', :as => :pricing
    match 'aboutus' => 'guests#aboutus', :as => :aboutus
    match 'aboutstmaarten' => 'guests#aboutstmaarten', :as => :stmaarten
    match 'availabilities' => 'calendar#index', :as => :availabilities
    match 'contactus' => 'contact#new', :as => :contactus
    match 'reservation' => 'events#index', :as => :reservation
  end  
 
 
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :end_at, :name, :start_at
  has_event_calendar
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # got these tips from
  # http://lyconic.com/blog/2010/08/03/dry-up-your-ajax-code-with-the-jquery-rest-plugin
  before_filter :correct_safari_and_ie_accept_headers, :set_locale
  after_filter :set_xhr_flash

  def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end  
  
  def set_xhr_flash
    flash.discard if request.xhr?
  end

  def correct_safari_and_ie_accept_headers
    ajax_request_types = ['text/javascript', 'application/json', 'text/xml']
    request.accepts.sort! { |x, y| ajax_request_types.include?(y.to_s) ? 1 : -1 } if request.xhr?
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month)
  end
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      flash[:notice] = "Message was successfully sent."
      redirect_to :controller => "guests"
    else
      flash[:error] = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  
  before_filter :authenticate_user!
  
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    render :layout => 'home'

  end

  def multimedia
    #render :layout => 'application'
  end

  def aboutus
    #render :layout => 'application'
  end
  
  def aboutstmaarten
    #render :layout => 'application'
  end
  
  def contactus
    #render :layout => 'application'
  end
  
  def included
    # render :layout => 'application'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/contact/new.html.erb
<div class="page-header">
  <h1><span class="icon-envelope"></span> Contact us</h1>
</div>

<% if flash[:notice] %>
  <p class="alert alert-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] %>
  <p class="alert alert-error"><%= flash[:error] %></p>
<% end %>

<%= form_for @message, :html => {:class => "form-horizontal"}, :url => contact_path do |form| %>
<fieldset>
  <div class="control-group">
    <label class="control-label" for="input01"><%= form.label :name %></label>
    <div class="controls">
     <%= form.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="input01"><%= form.label :email %></label>
    <div class="controls">
     <%= form.text_field :email, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="input01"><%= form.label :subject %></label>
    <div class="controls">
     <%= form.text_field :subject, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="textarea">Message</label>
    <div class="controls">
      <%= form.text_area :body, :class => "input-xlarge", :rows => "10" %>
    </div>
  </div>
  <div class="form-actions">
    <%= form.submit "Send", :class => "btn btn-primary" %>
  </div>
</fieldset>
  <% end %>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :start_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end_at, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.name %></td>
        <td><%= event.start_at %></td>
        <td><%= event.end_at %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @event.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @event.start_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @event.end_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/guests/aboutstmaarten.html.erb
<div class="page-header">
  <h1><span class="icon-picture"></span> <%= t "common.about_stmaarten" %></h1>
</div>

<p class="row">
	<%= t "aboutstmaarten.content_html" %>
</p>

app/views/guests/aboutus.html.erb
<div class="page-header">
  <h1><span class="icon-user"></span> <%= t "common.about_us" %></h1>
</div>
	<p class="alert alert-info">Once upon a time, we lived in Gatineau, Quebec and dreamed of a slower pace... and sunnier climes. After many trips to several different islands, we set our sights on St. Maarten, which turned out to be the best decision we ever made! We have been living here since September 2008 and are in our late thirties</p>
	<p class="row">
		<div class="span2"><h2>Our Island Home</h2></div>
		<div class="span2">
          <a href="#" class="thumbnail" data-bitly-type="bitly_hover_card">
            <img src="http://placehold.it/360x268" alt="">
          </a>
		</div>
		<div class="span4">
			MerSea Villa is located in a prestigious residential area called Dawn Beach Estates. This is a gated area, manned by a security guard 24 hours a day. The villa sits on a cliff, across the street from the sea, on a dead-end street. Privacy is excellent. The beach is a mere 5-minute walk to the beautiful powdery white-sands of Dawn Beach. Here is an idea of the distance to various attractions:
			<ul>
				<li>To Beach: 0.2 miles to Dawn Beach </li>
				<li>To Restaurant: 0.2 miles</li>
				<li>To Nearest Casino: 0.2 miles</li>
				<li>View it's location on <a href="http://maps.google.com/maps?q=http://gobeach.com/gobeach_earth/seawatch.kmz&t=k&om=1&z=16" target="_blank">Google Maps</a> or <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.gobeach.com%2Fgobeach_earth%2Fseawatch.kmz&sa=D&sntz=1&usg=AFQjCNG5j4mezJaR9OUtxBla3I-TIUKiBA" target="_blank">Google Earth</a></li>
			</ul>
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Julie</h2></div>
		<div class="span2">
		  <a href="/assets/julie-600.jpg" data-bitly-type="bitly_hover_card" rel="Julie">
            <%= image_tag("julie.jpg") %>
          </a>
		</div>
		<div class="span4">
			Hi there! I am a professional translator by trade. As you will see when meeting the rest of our family, I am a major animal lover. Most of the time, you will find me at my desk working away. I look forward to hearing from you and customizing a package just for you. I hope to see you soon!		
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Yannick</h2></div>
		<div class="span2">
		  <a href="/assets/yannick-600.jpg" data-bitly-type="bitly_hover_card" rel="Yannick">
            <%= image_tag("yannick.jpg") %>
          </a>
		</div>
		<div class="span4">
			Hello! I am a professional web developer, and I also have a black belt in jiu-jitsu... so you better pay your bill before you leave! Just kidding! Actually, I do have a black belt in jiu-jitsu and would be happy to give you self-defence classes during your stay. I can also be your driver, tour guide and concierge if you want me too... or I can make myself scarce and stay out of your hair if you prefer privacy.		
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Phénix</h2></div>
		<div class="span2">
		  <a href="/assets/phenix-600.jpg" data-bitly-type="bitly_hover_card" rel="Phénix">
            <%= image_tag("phenix.jpg") %>
          </a>
		</div>
		<div class="span4">
			Phénix is a black standard poodle and can be a rambunctious boy at times! He loves to play and give kisses, but is also our best watchdog.		
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Jesse</h2></div>
		<div class="span2">
		  <a href="/assets/jesse-600.jpg" data-bitly-type="bitly_hover_card" rel="Jesse">
            <%= image_tag("jesse.jpg") %>
          </a>
		</div>
		<div class="span4">
			Jesse is also a black standard poodle, but much more laid back and independent. A retired show dog turned “island dog!”		
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Ziggy</h2></div>
		<div class="span2">
          <a href="#" class="thumbnail" data-bitly-type="bitly_hover_card">
            <img src="http://placehold.it/360x268" alt="">
          </a>
		</div>
		<div class="span4">
			Ziggy is a little escape artist found flying around the home of Tony and Michaëlle, our pool maintenance crew. He is a little bird with a big personality! He is a peach faced lovebird.		
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Fripouille and Fripon</h2></div>
		<div class="span2">
		  <a href="/assets/fripon-600.jpg" data-bitly-type="bitly_hover_card" rel="Fripouille and Fripon">
            <%= image_tag("fripon.jpg") %>
          </a>
		</div>
		<div class="span4">
			Fripouille and Fripon are two male Indian ringneck parrots. They cannot talk yet but is still pretty young. They are both a little timid with strangers but enjoy green beans and hot peppers from our garden, as does Ziggy. All three birds love to sing and dance when they see wild birds flying by. We get lots of sea birds by the way... pelicans, seagulls, frigates, etc. We even have a wild macaw regularly flying with the seagulls in the neighbourhood.		
		</div>
	</p>
	<p class="row">
		<div class="span2"><h2>Caroline</h2></div>
		<div class="span2">
		  <a href="/assets/caroline-600.jpg" data-bitly-type="bitly_hover_card">
            <%= image_tag("caroline.jpg") %>
          </a>
		</div>
		<div class="span4">
		</div>
	</p>

app/views/guests/included.html.erb
<div class="page-header">
  <h1><span class="icon-briefcase"></span> <%= t "common.whats_included" %></h1>
</div>

<p class="row">
<p>We live in a 3500 sq. ft. 4-bedroom villa. Your bedroom opens to the terrace, where a very large infinity pool, a jetted plunge pool and lounge chairs are at your disposal. The house sits on a cliff by the sea, so you have an amazing ocean view from your bedroom and you can hear the waves crashing right down below. The tradewinds are constant, so the A/C is rarely necessary. However, you can also use the independently-operated A/C unit in your bedroom if you prefer your room cooler. Your bedroom also has a complete private bathroom with large shower, a king-size bed and a minifridge. Linens, bath and beach towels, a hairdryer and some toiletries are provided. We serve fresh croissants, tropical fruits, orange juice and coffee or tea in the morning.</p>
<h2>Included</h2>	
<table class="table table-striped">
	<thead>
	  <tr>
	    <th>Description</th>
	    <th>Note</th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
	    <td>Tour of the Island, drive to the best beach on the island and a day of shopping</td>
	    <td></td>
	  </tr>		
	  <tr>
	    <td>Fridge</td>
	    <td>Includes for free x beers, 1 bottle of wine, x soda, etc...</td>
	  </tr>
	  <tr>
	    <td>Airport transfers</td>
	    <td></td>
	  </tr>
	  <tr>
	    <td>Daily continental breakfast for two served on the patio or in your room</td>
	    <td></td>
	  </tr>
	  <tr>
	    <td>Daily housekeeping</td>
	    <td></td>
	  </tr>
	  <tr>
	    <td>Use of the pool</td>
	    <td></td>
	  </tr>
	  <tr>
	    <td>Use of the jacuzzi</td>
	    <td></td>
	  </tr>
	  <tr>
	    <td>Complimentary movie nights in your very own outdoor theater by the sea under the stars (pizza included)</td>
	    <td></td>
	  </tr>	  
	  <tr>
	    <td>Linens, bath towels and beach towels</td>
	    <td></td>
	  </tr>	
	  <tr>
	    <td>Shampoo, conditioner and body lotion</td>
	    <td></td>
	  </tr>	
	  <tr>
	    <td>Hair dryer</td>
	    <td></td>
	  </tr>	
	  <tr>
	    <td>TV</td>
	    <td>Don't include any Cable TV.  We provide a library of movies you can watch.</td>
	  </tr>	
	  <tr>
	    <td>Cellular</td>
	    <td>No fees for any local calls</td>
	  </tr>	
	</tbody>
</table>
<h2>NOT Included</h2>	
<table class="table table-striped">
	<thead>
	  <tr>
	    <th>Description</th>
	    <th>Note</th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
	    <td>Kitchen</td>
	    <td>5 minutes walk from the Westin Restaurants.  We can even get them for you.</td>
	  </tr>
	</tbody>
</table>
</p>

app/views/guests/pricing.html.erb
<div class="page-header">
  <h1><span class="icon-tag"></span> <%= t "common.pricing" %></h1>
</div>

<p class="row">
<%= t "pricing.content_html" %>
</p>

app/views/shared/_menu.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
			<a class="brand" href="#">MERSEA VILL&#581;</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="active">testok
						<%= link_to "Home", root_path %>
					</li>
					<li>
						<%= link_to "Pictures", multimedia_path %>
					</li>
					<li>
						<%= link_to "What's include", included_path %>
					</li>
					<li>
						<%= link_to "Pricing", pricing_path %>
					</li>
					<li>
						<%= link_to "About us", aboutus_path %>
					</li>
					<li>
						<%= link_to "About St. Maarten", stmaarten_path %>
					</li>
					<li>
						<%= link_to "Availabilities", availabilities_path %>
					</li>
					<li>
						<%= link_to "Contact us", contactus_path %>
					</li>
					<% if user_signed_in? %>
					<li>
						<%= link_to "Reservations", :controller => "events" %>
					</li>
					<li>
						<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
					</li>
					<% else %>
					<li>
						<%= link_to "sign in", new_user_session_path %>
					</li>
					<% end %>
					<% if I18n.locale == I18n.default_locale %>
					<li>
						<%= link_to "Français", :locale=>'fr'%>
					</li>
					<% else %>
					<li>
						<%= link_to "English", :locale=>'en'%>
					</li>
					<%end%>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:sign_in_count) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>